## Generate embeddings and response

from google import genai
from google.genai import types
import dotenv
import os
dotenv.load_dotenv()
os.environ.get("GEMINI_API_KEY")

OUTPUT_DIM=768

client = genai.Client()

class Gemini:
    def __init__(self, model_name: str):
        self.model_name = model_name
        self.client = genai.Client()

    def embed_content(self, contents, task_type) -> list[float]:
        """
        Create and return the embedding generated by Gemini as list[float]
        task_types: "RETRIEVAL_DOCUMENT", "RETRIEVAL_QUERY"
        """
        try:
            response = self.client.models.embed_content(
            model=self.model_name,
            contents=contents,
            config=types.EmbedContentConfig(task_type=task_type, output_dimensionality=OUTPUT_DIM))
        except:
            raise Exception("Error embedding content")

        return response.embeddings[0].values
    
    def generate_response(self, prompt):
        try:
            final_response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            )
        except ValueError as e:
            raise Exception(f"Error generating response: {e}")

        return final_response.text





# if __name__ == "__main__":
#     try:
#         app = firebase_admin.get_app()
#     except ValueError as e:
#         cred = credentials.Certificate('/home/george/GreatUniHack/GreatUniHack2025/src/services/space-mouse-4803e-firebase-adminsdk-fbsvc-98226ecde3.json')
#         firebase_admin.initialize_app(cred)
    
#     texts = ["I heard you can eat carrots and potatoes on mars"]
#     gemini = Gemini("gemini-embedding-001")
#     embedding = gemini.embed_content(texts, "RETRIEVAL_DOCUMENT")
#     store = Firestore()
#     store.save_to_collection("mars", embedding, texts)

#     print(gemini.generate_response(store.generate_prompt(gemini, "mars")))
